default_stages: [commit]

default_language_version:
  python: python3.12

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-toml
          - id: check-yaml

    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: 'v1.10.0'
      hooks:
          - id: python-check-blanket-noqa
          - id: python-check-blanket-type-ignore
          - id: python-check-mock-methods
          - id: python-no-eval
          - id: python-use-type-annotations

    - repo: local
      hooks:
          - id: python-check-blanket-nosec
            name: check blanket nosec
            entry: '# nosec(?!: (B[0-9]{3} ?)+( +#.*)*$)'
            language: pygrep
            types: [python]

    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: 'v0.10.0.1'
      hooks:
          - id: shellcheck
            args: ['-x']

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: 'v0.6.7'
      hooks:
          - id: ruff
            args: ['--exit-non-zero-on-fix']

    - repo: https://github.com/PyCQA/bandit
      rev: '1.7.9'
      hooks:
          - id: bandit
            additional_dependencies: ['.[toml]']
            args: ['-c', 'pyproject.toml', '--exclude', 'tests']

    - repo: https://github.com/rubik/xenon/
      rev: 'v0.9.1'
      hooks:
          - id: xenon
            name: xenon
            files: 'cli'
            args: ["--max-average=A", "--max-modules=A", "--max-absolute=A"]

    - repo: https://github.com/python-poetry/poetry
      rev: '1.8.3'
      hooks:
          - id: poetry-check
          - id: poetry-lock
            args: ["--no-update"]
          - id: poetry-install
