name: docker
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Install poetry
        run: pip install poetry==1.8.3

      - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Install local project
        run: make init

      - name: Unit tests
        run: make tests
