name: pre-commit
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  style-check:
    name: Style Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Install pre-commit
        run: pip install poetry==1.8.3

      - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install

      - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        env:
          cache-name: cache-pre-commit
        with:
          path: ~/.cache/pre-commit
          key: ${{ env.cache-name }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        run: SKIP=poetry-lock poetry run pre-commit run --show-diff-on-failure --all-files
