name: semgrep
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  static:
    name: Static Check
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - run: semgrep ci --config=p/default
